# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: task/task.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'task/task.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftask/task.proto\x12\x1etaskprocessservice.taskpb.task\"H\n\x05\x44\x65\x62ug\x12\x10\n\x08\x64\x65\x62ug_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x10\n\x08trace_id\x18\x03 \x01(\t\x12\n\n\x02ip\x18\x04 \x01(\t\"\x12\n\x10\x46\x65tchTaskRequest\"\x7f\n\x11\x46\x65tchTaskResponse\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x36\n\x06status\x18\x02 \x01(\x0e\x32&.taskprocessservice.taskpb.task.Status\x12\x12\n\ncreated_at\x18\x03 \x01(\x03\x12\x12\n\nupdated_at\x18\x04 \x01(\x03\"\x92\x01\n\x14\x46\x65tchTaskBaseRequest\x12\x34\n\x05\x64\x65\x62ug\x18\x01 \x01(\x0b\x32%.taskprocessservice.taskpb.task.Debug\x12\x44\n\nfetch_task\x18\x02 \x01(\x0b\x32\x30.taskprocessservice.taskpb.task.FetchTaskRequest\"\x9e\x01\n\x15\x46\x65tchTaskBaseResponse\x12\r\n\x05\x65rror\x18\x01 \x01(\x08\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x15\n\rerror_message\x18\x03 \x01(\t\x12N\n\x13\x66\x65tch_task_response\x18\x04 \x03(\x0b\x32\x31.taskprocessservice.taskpb.task.FetchTaskResponse\"K\n\x11UpdateTaskRequest\x12\x36\n\x06status\x18\x02 \x01(\x0e\x32&.taskprocessservice.taskpb.task.Status\"X\n\x12UpdateTaskResponse\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x36\n\x06status\x18\x02 \x01(\x0e\x32&.taskprocessservice.taskpb.task.Status\"\x95\x01\n\x15UpdateTaskBaseRequest\x12\x34\n\x05\x64\x65\x62ug\x18\x01 \x01(\x0b\x32%.taskprocessservice.taskpb.task.Debug\x12\x46\n\x0bupdate_task\x18\x02 \x01(\x0b\x32\x31.taskprocessservice.taskpb.task.UpdateTaskRequest\"\xa1\x01\n\x16UpdateTaskBaseResponse\x12\r\n\x05\x65rror\x18\x01 \x01(\x08\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x15\n\rerror_message\x18\x03 \x01(\t\x12P\n\x14update_task_response\x18\x04 \x01(\x0b\x32\x32.taskprocessservice.taskpb.task.UpdateTaskResponse*T\n\x06Status\x12\x12\n\x0e\x44\x45\x46\x41ULT_STATUS\x10\x00\x12\x0b\n\x07PENDING\x10\x01\x12\x0e\n\nPROCESSING\x10\x02\x12\r\n\tCOMPLETED\x10\x03\x12\n\n\x06\x46\x41ILED\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'task.task_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATUS']._serialized_start=1067
  _globals['_STATUS']._serialized_end=1151
  _globals['_DEBUG']._serialized_start=51
  _globals['_DEBUG']._serialized_end=123
  _globals['_FETCHTASKREQUEST']._serialized_start=125
  _globals['_FETCHTASKREQUEST']._serialized_end=143
  _globals['_FETCHTASKRESPONSE']._serialized_start=145
  _globals['_FETCHTASKRESPONSE']._serialized_end=272
  _globals['_FETCHTASKBASEREQUEST']._serialized_start=275
  _globals['_FETCHTASKBASEREQUEST']._serialized_end=421
  _globals['_FETCHTASKBASERESPONSE']._serialized_start=424
  _globals['_FETCHTASKBASERESPONSE']._serialized_end=582
  _globals['_UPDATETASKREQUEST']._serialized_start=584
  _globals['_UPDATETASKREQUEST']._serialized_end=659
  _globals['_UPDATETASKRESPONSE']._serialized_start=661
  _globals['_UPDATETASKRESPONSE']._serialized_end=749
  _globals['_UPDATETASKBASEREQUEST']._serialized_start=752
  _globals['_UPDATETASKBASEREQUEST']._serialized_end=901
  _globals['_UPDATETASKBASERESPONSE']._serialized_start=904
  _globals['_UPDATETASKBASERESPONSE']._serialized_end=1065
# @@protoc_insertion_point(module_scope)
