"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _Status:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _StatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Status.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    DEFAULT_STATUS: _Status.ValueType  # 0
    PENDING: _Status.ValueType  # 1
    PROCESSING: _Status.ValueType  # 2
    COMPLETED: _Status.ValueType  # 3
    FAILED: _Status.ValueType  # 4

class Status(_Status, metaclass=_StatusEnumTypeWrapper): ...

DEFAULT_STATUS: Status.ValueType  # 0
PENDING: Status.ValueType  # 1
PROCESSING: Status.ValueType  # 2
COMPLETED: Status.ValueType  # 3
FAILED: Status.ValueType  # 4
global___Status = Status

@typing.final
class Debug(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DEBUG_ID_FIELD_NUMBER: builtins.int
    USER_ID_FIELD_NUMBER: builtins.int
    TRACE_ID_FIELD_NUMBER: builtins.int
    IP_FIELD_NUMBER: builtins.int
    debug_id: builtins.str
    user_id: builtins.str
    trace_id: builtins.str
    ip: builtins.str
    def __init__(
        self,
        *,
        debug_id: builtins.str = ...,
        user_id: builtins.str = ...,
        trace_id: builtins.str = ...,
        ip: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["debug_id", b"debug_id", "ip", b"ip", "trace_id", b"trace_id", "user_id", b"user_id"]) -> None: ...

global___Debug = Debug

@typing.final
class FetchTaskRequest(google.protobuf.message.Message):
    """fetch data"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___FetchTaskRequest = FetchTaskRequest

@typing.final
class FetchTaskResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    UPDATED_AT_FIELD_NUMBER: builtins.int
    id: builtins.int
    status: global___Status.ValueType
    created_at: builtins.int
    updated_at: builtins.int
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        status: global___Status.ValueType = ...,
        created_at: builtins.int = ...,
        updated_at: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["created_at", b"created_at", "id", b"id", "status", b"status", "updated_at", b"updated_at"]) -> None: ...

global___FetchTaskResponse = FetchTaskResponse

@typing.final
class FetchTaskBaseRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DEBUG_FIELD_NUMBER: builtins.int
    FETCH_TASK_FIELD_NUMBER: builtins.int
    @property
    def debug(self) -> global___Debug: ...
    @property
    def fetch_task(self) -> global___FetchTaskRequest: ...
    def __init__(
        self,
        *,
        debug: global___Debug | None = ...,
        fetch_task: global___FetchTaskRequest | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["debug", b"debug", "fetch_task", b"fetch_task"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["debug", b"debug", "fetch_task", b"fetch_task"]) -> None: ...

global___FetchTaskBaseRequest = FetchTaskBaseRequest

@typing.final
class FetchTaskBaseResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ERROR_FIELD_NUMBER: builtins.int
    SUCCESS_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    FETCH_TASK_RESPONSE_FIELD_NUMBER: builtins.int
    error: builtins.bool
    success: builtins.bool
    error_message: builtins.str
    @property
    def fetch_task_response(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___FetchTaskResponse]: ...
    def __init__(
        self,
        *,
        error: builtins.bool = ...,
        success: builtins.bool = ...,
        error_message: builtins.str = ...,
        fetch_task_response: collections.abc.Iterable[global___FetchTaskResponse] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["error", b"error", "error_message", b"error_message", "fetch_task_response", b"fetch_task_response", "success", b"success"]) -> None: ...

global___FetchTaskBaseResponse = FetchTaskBaseResponse

@typing.final
class UpdateTaskRequest(google.protobuf.message.Message):
    """update"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATUS_FIELD_NUMBER: builtins.int
    status: global___Status.ValueType
    def __init__(
        self,
        *,
        status: global___Status.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["status", b"status"]) -> None: ...

global___UpdateTaskRequest = UpdateTaskRequest

@typing.final
class UpdateTaskResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    id: builtins.int
    status: global___Status.ValueType
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        status: global___Status.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["id", b"id", "status", b"status"]) -> None: ...

global___UpdateTaskResponse = UpdateTaskResponse

@typing.final
class UpdateTaskBaseRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DEBUG_FIELD_NUMBER: builtins.int
    UPDATE_TASK_FIELD_NUMBER: builtins.int
    @property
    def debug(self) -> global___Debug: ...
    @property
    def update_task(self) -> global___UpdateTaskRequest: ...
    def __init__(
        self,
        *,
        debug: global___Debug | None = ...,
        update_task: global___UpdateTaskRequest | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["debug", b"debug", "update_task", b"update_task"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["debug", b"debug", "update_task", b"update_task"]) -> None: ...

global___UpdateTaskBaseRequest = UpdateTaskBaseRequest

@typing.final
class UpdateTaskBaseResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ERROR_FIELD_NUMBER: builtins.int
    SUCCESS_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    UPDATE_TASK_RESPONSE_FIELD_NUMBER: builtins.int
    error: builtins.bool
    success: builtins.bool
    error_message: builtins.str
    @property
    def update_task_response(self) -> global___UpdateTaskResponse: ...
    def __init__(
        self,
        *,
        error: builtins.bool = ...,
        success: builtins.bool = ...,
        error_message: builtins.str = ...,
        update_task_response: global___UpdateTaskResponse | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["update_task_response", b"update_task_response"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["error", b"error", "error_message", b"error_message", "success", b"success", "update_task_response", b"update_task_response"]) -> None: ...

global___UpdateTaskBaseResponse = UpdateTaskBaseResponse
