# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from taskconsumerservice.taskpb.task import task_pb2 as task_dot_task__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in task/task_rpc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TaskRpcStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.fetchTask = channel.unary_unary(
                '/taskprocessservice.taskpb.task.TaskRpc/fetchTask',
                request_serializer=task_dot_task__pb2.FetchTaskBaseRequest.SerializeToString,
                response_deserializer=task_dot_task__pb2.FetchTaskBaseResponse.FromString,
                _registered_method=True)
        self.updateTaskStatus = channel.unary_unary(
                '/taskprocessservice.taskpb.task.TaskRpc/updateTaskStatus',
                request_serializer=task_dot_task__pb2.UpdateTaskBaseRequest.SerializeToString,
                response_deserializer=task_dot_task__pb2.UpdateTaskBaseResponse.FromString,
                _registered_method=True)


class TaskRpcServicer(object):
    """Missing associated documentation comment in .proto file."""

    def fetchTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def updateTaskStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TaskRpcServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'fetchTask': grpc.unary_unary_rpc_method_handler(
                    servicer.fetchTask,
                    request_deserializer=task_dot_task__pb2.FetchTaskBaseRequest.FromString,
                    response_serializer=task_dot_task__pb2.FetchTaskBaseResponse.SerializeToString,
            ),
            'updateTaskStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.updateTaskStatus,
                    request_deserializer=task_dot_task__pb2.UpdateTaskBaseRequest.FromString,
                    response_serializer=task_dot_task__pb2.UpdateTaskBaseResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'taskprocessservice.taskpb.task.TaskRpc', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('taskprocessservice.taskpb.task.TaskRpc', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TaskRpc(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def fetchTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taskprocessservice.taskpb.task.TaskRpc/fetchTask',
            task_dot_task__pb2.FetchTaskBaseRequest.SerializeToString,
            task_dot_task__pb2.FetchTaskBaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def updateTaskStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taskprocessservice.taskpb.task.TaskRpc/updateTaskStatus',
            task_dot_task__pb2.UpdateTaskBaseRequest.SerializeToString,
            task_dot_task__pb2.UpdateTaskBaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
